/**
 * Server-side album-photo thumbnail generation (issue #139).
 *
 * A full-resolution phone photo (often several MB) rendered into a ~140px album tile is a large, wasteful
 * transfer that the browser then throws away by downscaling in CSS. This module produces a small JPEG
 * thumbnail with `sharp` and stores it in the SAME MediaStorage as the original, at a deterministic
 * derived key. The audited serve route (`/api/album-photo/[photoId]`) serves the thumbnail for the grid
 * and the original for the full-size/detail view — both behind the identical authorization gate.
 *
 * WHERE THUMBNAILS ARE MADE (decision, see docs):
 *   - PROACTIVELY, at record/import time (`warmThumbnail`), while the just-stored bytes are already in
 *     memory for EXIF — so a new upload's thumbnail exists the moment its tile first paints.
 *   - LAZILY, on the first thumbnail request in the serve route, for photos that predate this feature
 *     (BACKFILL) or whose proactive warm failed. One code path covers new uploads, Google imports, and
 *     every existing photo — no separate backfill script.
 *
 * `sharp` is confined to this file (apps/web). It must NEVER be imported into the `@chronicle/*`
 * vendor-seam packages; the pipeline architecture guard (packages/pipeline/test/pipeline.test.ts) fails
 * CI on a `sharp` import anywhere in those src trees.
 */
import "server-only";
import sharp from "sharp";
import type { MediaStorage } from "@chronicle/storage";

/**
 * Longest edge of a generated thumbnail, in px. The grid renders tiles up to ~280px wide (the size
 * slider's max) and the masonry/list variants are smaller; 480 covers those at 2× (retina) density
 * while staying an order of magnitude smaller than a full-res original. Used in sharp resize math.
 */
export const THUMBNAIL_MAX_EDGE_PX = 480;
/** JPEG quality (1–100) for thumbnails — tuned for small tiles where mild artifacts are invisible. */
export const THUMBNAIL_JPEG_QUALITY = 72;
/** The content type every generated thumbnail is encoded as (sharp `.jpeg()` below). */
export const THUMBNAIL_CONTENT_TYPE = "image/jpeg";

/** Suffix appended to the original storage key to derive its thumbnail's key (same keyspace). */
const THUMBNAIL_KEY_SUFFIX = ".thumb";

/**
 * The storage key a photo's thumbnail lives at, derived deterministically from the original key. The
 * original is a server-minted `family-photos/<uuid>`; the thumbnail sits beside it as
 * `family-photos/<uuid>.thumb`. Deterministic derivation means the lean album row (ADR-0009, which
 * stores only the original `storageKey`) needs no new column to locate the thumbnail.
 */
export function thumbnailStorageKey(originalKey: string): string {
  return `${originalKey}${THUMBNAIL_KEY_SUFFIX}`;
}

/**
 * Downscale image bytes to a thumbnail JPEG. `.rotate()` (no args) bakes in the EXIF orientation so a
 * portrait phone photo is not served sideways; `fit: "inside"` + `withoutEnlargement` preserves aspect
 * ratio and never upscales a photo already smaller than the box. THROWS on bytes sharp cannot decode
 * (non-image / corrupt) — callers decide how to degrade.
 */
export async function generateThumbnailBytes(bytes: Uint8Array): Promise<Uint8Array> {
  const out = await sharp(Buffer.from(bytes))
    .rotate()
    .resize(THUMBNAIL_MAX_EDGE_PX, THUMBNAIL_MAX_EDGE_PX, {
      fit: "inside",
      withoutEnlargement: true,
    })
    .jpeg({ quality: THUMBNAIL_JPEG_QUALITY })
    .toBuffer();
  return new Uint8Array(out.buffer, out.byteOffset, out.byteLength);
}

/**
 * Generate a photo's thumbnail from its original bytes and store it at the derived key, returning the
 * thumbnail bytes (or null if generation failed). BEST-EFFORT and total: it never throws, so a caller
 * on a hot path (upload/import record, or the serve route) can `await` it without a try/catch and
 * without risking the primary operation.
 *
 *   - A `sharp` failure (non-image / corrupt bytes) ⇒ logs, writes a 0-byte SENTINEL at the derived
 *     key, and returns null; the caller degrades (the record still succeeds; the serve route falls
 *     back to the full-res original). The sentinel (issue #176) makes the failure sticky: without it
 *     every later thumbnail request would re-fetch the original and re-run `sharp` only to fail
 *     again — repeated CPU-intensive work and log flooding for every bad file on every page load.
 *   - The `storage.put` is write-once; a concurrent warmer that already wrote the key raises
 *     `ObjectAlreadyExistsError`, which is swallowed — the freshly generated bytes are still returned,
 *     so a racing serve request serves a correct thumbnail regardless of who won the write.
 */
export async function warmThumbnail(
  storage: MediaStorage,
  originalKey: string,
  originalBytes: Uint8Array,
): Promise<Uint8Array | null> {
  let thumb: Uint8Array;
  try {
    thumb = await generateThumbnailBytes(originalBytes);
  } catch (err) {
    console.error(
      `[album/thumbnail] generation failed for ${originalKey}:`,
      err instanceof Error ? err.message : String(err),
    );
    // Write a 0-byte sentinel so later requests serve the original straight from the fast path
    // instead of re-running `sharp` on bytes it can never decode (issue #176). A write-once
    // conflict (a concurrent warmer won) or a store error is harmless — worst case we retry.
    try {
      await storage.put({
        key: thumbnailStorageKey(originalKey),
        bytes: new Uint8Array(0),
        contentType: "application/octet-stream",
      });
    } catch {
      // Sentinel is best-effort; a miss only means one more failed generation attempt.
    }
    return null;
  }
  try {
    await storage.put({
      key: thumbnailStorageKey(originalKey),
      bytes: thumb,
      contentType: THUMBNAIL_CONTENT_TYPE,
    });
  } catch {
    // Write-once conflict (a concurrent warmer won) or a transient store error — harmless: the
    // thumbnail either already exists or will be regenerated on the next request. Return the bytes.
  }
  return thumb;
}
