/**
 * FROZEN section registry for the Account surface (ADR-0029). The single source of truth for the
 * ordered set of sections, their route slugs, and the component that renders each.
 *
 * SHARED CONTRACT — do NOT edit this file to fill in a section's real content. Each of the 7
 * sections is owned by a parallel agent who replaces ONLY `./sections/<slug>/index.tsx` (its
 * default export) and, if it needs copy, adds `./sections/<slug>/copy.ts`. This registry, the
 * `AccountSectionProps` type, the layout, and `[section]/page.tsx` are the frozen shell around them.
 */
import type { ComponentType } from "react";
import type { AccountSectionProps } from "./section-props";

import ProfileSection from "./sections/profile";
import AppearanceSection from "./sections/appearance";
import NarrationSection from "./sections/narration";
import PrivacySection from "./sections/privacy";
import NotificationsSection from "./sections/notifications";
import MemoriesSection from "./sections/memories";
import FamiliesSection from "./sections/families";

export interface AccountSection {
  /** URL slug: /hub/account/<slug>. Also the section's stable key. */
  readonly slug: string;
  /** Left-rail label. */
  readonly label: string;
  /** The section's server component — its default export. Rendered with `AccountSectionProps`. */
  readonly Component: ComponentType<AccountSectionProps>;
}

/**
 * The ordered sections. Order IS the rail order and the drill-down list order. Do not reorder or
 * add/remove entries without an ADR-0029 amendment — the redirects and deep links depend on these
 * exact slugs.
 */
export const ACCOUNT_SECTIONS: readonly AccountSection[] = [
  { slug: "profile", label: "Profile", Component: ProfileSection },
  { slug: "appearance", label: "Appearance", Component: AppearanceSection },
  { slug: "narration", label: "Narration", Component: NarrationSection },
  { slug: "privacy", label: "Privacy", Component: PrivacySection },
  { slug: "notifications", label: "Notifications", Component: NotificationsSection },
  { slug: "memories", label: "Memories", Component: MemoriesSection },
  { slug: "families", label: "Families", Component: FamiliesSection },
] as const;

/** Look up a section by its slug. Returns undefined for an unknown slug (the page 404s). */
export function findAccountSection(slug: string): AccountSection | undefined {
  return ACCOUNT_SECTIONS.find((s) => s.slug === slug);
}

export type { AccountSectionProps } from "./section-props";
