"use client";

/**
 * Account surface rail + drill-down (ADR-0029). On wide viewports this is a persistent left rail (one
 * link per section, active state from the pathname). On a phone the rail is hidden until the panel's
 * "Sections" toggle opens it as a pushed overlay list; picking a section navigates and closes it —
 * the drill-down. Purely CSS-driven layout (account-shell.module.css); this component owns only the
 * open/closed state and active-link derivation, so there is no vertical bloat on mobile.
 *
 * Part of the FROZEN shell — section agents do NOT edit this file.
 */
import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { AccountSection } from "./account-sections";
import styles from "./account-shell.module.css";

export interface AccountRailProps {
  /** Slug + label for each section, in registry order. */
  sections: readonly Pick<AccountSection, "slug" | "label">[];
  /** Copy for the narrow-only sections toggle and the back-to-hub link. */
  copy: { sectionsLabel: string; backToHub: string };
}

export function AccountRail({ sections, copy }: AccountRailProps) {
  const [open, setOpen] = useState(false);
  const pathname = usePathname();
  const activeSlug = sections.find((s) => pathname === `/hub/account/${s.slug}`)?.slug;

  return (
    <>
      <div className={styles.topBar}>
        <Link href="/hub" className={styles.backLink}>
          {copy.backToHub}
        </Link>
        <button
          type="button"
          className={styles.sectionsToggle}
          aria-expanded={open}
          onClick={() => setOpen((v) => !v)}
        >
          {copy.sectionsLabel}
        </button>
      </div>

      <nav
        aria-label={copy.sectionsLabel}
        className={open ? styles.railOpen : styles.rail}
      >
        <div className={styles.railNav}>
          {sections.map((s) => (
            <Link
              key={s.slug}
              href={`/hub/account/${s.slug}`}
              className={styles.railLink}
              aria-current={s.slug === activeSlug ? "page" : undefined}
              onClick={() => setOpen(false)}
            >
              <span>{s.label}</span>
            </Link>
          ))}
        </div>
      </nav>
    </>
  );
}
