/**
 * FROZEN section registry for the Account surface (ADR-0029). The single source of truth for the
 * ordered set of sections, their route slugs, their scope, and the component that renders each.
 *
 * SHARED CONTRACT — do NOT edit this file to fill in a section's real content. Each of the 7
 * sections is owned by a parallel agent who replaces ONLY `./sections/<slug>/index.tsx` (its
 * default export) and, if it needs copy, adds `./sections/<slug>/copy.ts`. This registry, the
 * `AccountSectionProps` type, the layout, and `[section]/page.tsx` are the frozen shell around them.
 *
 * `scope` labels whether the section's settings are device-local (browser-applied app preferences,
 * ADR-0020) or account-level (server-persisted, cross-device). It is metadata for the section UI to
 * render a scope hint; the shell itself is storage-agnostic.
 */
import type { ComponentType } from "react";
import type { AccountSectionProps } from "./section-props";

import ProfileSection from "./sections/profile";
import AppearanceSection from "./sections/appearance";
import NarrationSection from "./sections/narration";
import PrivacySection from "./sections/privacy";
import NotificationsSection from "./sections/notifications";
import MemoriesSection from "./sections/memories";
import FamiliesSection from "./sections/families";

export type AccountSectionScope = "device" | "account";

export interface AccountSection {
  /** URL slug: /hub/account/<slug>. Also the section's stable key. */
  readonly slug: string;
  /** Left-rail label. */
  readonly label: string;
  /** device = browser-applied app preference (ADR-0020); account = server-persisted, cross-device. */
  readonly scope: AccountSectionScope;
  /** The section's server component — its default export. Rendered with `AccountSectionProps`. */
  readonly Component: ComponentType<AccountSectionProps>;
}

/**
 * The ordered sections. Order IS the rail order and the drill-down list order. Do not reorder or
 * add/remove entries without an ADR-0029 amendment — the redirects and deep links depend on these
 * exact slugs.
 */
export const ACCOUNT_SECTIONS: readonly AccountSection[] = [
  { slug: "profile", label: "Profile", scope: "account", Component: ProfileSection },
  { slug: "appearance", label: "Appearance", scope: "device", Component: AppearanceSection },
  { slug: "narration", label: "Narration", scope: "account", Component: NarrationSection },
  { slug: "privacy", label: "Privacy", scope: "account", Component: PrivacySection },
  { slug: "notifications", label: "Notifications", scope: "account", Component: NotificationsSection },
  { slug: "memories", label: "Memories", scope: "account", Component: MemoriesSection },
  { slug: "families", label: "Families", scope: "account", Component: FamiliesSection },
] as const;

/** Look up a section by its slug. Returns undefined for an unknown slug (the page 404s). */
export function findAccountSection(slug: string): AccountSection | undefined {
  return ACCOUNT_SECTIONS.find((s) => s.slug === slug);
}

export type { AccountSectionProps } from "./section-props";
