/**
 * Shell scaffold — the "coming soon" placeholder each section stub renders until its parallel agent
 * fills in the real content. Part of the FROZEN shell (not owned by a section agent). Section agents
 * replace their own `sections/<slug>/index.tsx` default export; they do NOT edit this file.
 */
import type { CSSProperties } from "react";

export function SectionPlaceholder({ label }: { label: string }) {
  return (
    <section aria-labelledby="account-section-title">
      <h2 id="account-section-title" style={title}>
        {label}
      </h2>
      <p style={note}>Coming soon.</p>
    </section>
  );
}

const title: CSSProperties = {
  fontFamily: "var(--font-story)",
  fontSize: "clamp(1.5rem, 3.5vw, var(--text-display))",
  fontWeight: 400,
  color: "var(--text-body)",
  margin: "0 0 8px",
};

const note: CSSProperties = {
  fontFamily: "var(--font-ui)",
  fontSize: "var(--text-ui-sm)",
  color: "var(--text-muted)",
  margin: 0,
};
