-- GENERATED by `pnpm --filter @chronicle/db db:generate` (drizzle-kit export from src/schema.ts).
-- The single full-schema DDL. Do NOT hand-edit — edit src/schema.ts and regenerate.
-- Structural invariants drizzle can't model (triggers, partial unique indexes) live in
-- invariants.sql and are applied right after this file. See src/migrate.ts.

CREATE TYPE "public"."ask_status" AS ENUM('queued', 'routed', 'answered');
CREATE TYPE "public"."audience_tier" AS ENUM('private', 'branch', 'family', 'public');
CREATE TYPE "public"."consent_action" AS ENUM('approved_for_sharing', 'set_audience_tier', 'revoked', 'paused_membership');
CREATE TYPE "public"."follow_up_outcome" AS ENUM('answered', 'skipped', 'off_ramped');
CREATE TYPE "public"."follow_up_record_kind" AS ENUM('decision', 'outcome');
CREATE TYPE "public"."intake_origin" AS ENUM('voice', 'typed');
CREATE TYPE "public"."invitation_status" AS ENUM('pending', 'accepted', 'revoked', 'expired');
CREATE TYPE "public"."join_request_status" AS ENUM('pending', 'approved', 'declined');
CREATE TYPE "public"."kinship_edge_type" AS ENUM('parent_of', 'partnered_with');
CREATE TYPE "public"."kinship_nature" AS ENUM('biological', 'adoptive', 'step', 'foster', 'unknown');
CREATE TYPE "public"."kinship_state" AS ENUM('asserted', 'affirmed', 'denied', 'corrected');
CREATE TYPE "public"."life_status" AS ENUM('living', 'deceased');
CREATE TYPE "public"."media_kind" AS ENUM('story_audio', 'approval_audio', 'intake_audio', 'caption_audio', 'photo', 'document');
CREATE TYPE "public"."membership_role" AS ENUM('narrator', 'member', 'steward');
CREATE TYPE "public"."membership_status" AS ENUM('active', 'paused', 'ended');
CREATE TYPE "public"."person_origin" AS ENUM('self', 'invitee', 'mention');
CREATE TYPE "public"."person_sex" AS ENUM('male', 'female', 'unknown');
CREATE TYPE "public"."photo_source" AS ENUM('upload', 'google_picker');
CREATE TYPE "public"."prose_revision_level" AS ENUM('user_authored', 'ai_transcribed', 'ai_cleaned', 'ai_polished', 'human_corrected', 'ai_verified', 'human_metadata_edit');
CREATE TYPE "public"."story_image_provenance" AS ENUM('family_photo', 'illustration');
CREATE TYPE "public"."story_kind" AS ENUM('voice', 'text');
CREATE TYPE "public"."story_state" AS ENUM('draft', 'pending_approval', 'approved', 'shared', 'archived');
CREATE TABLE "account_contacts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"value" text NOT NULL,
	"verified_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "account_identities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"account_id" uuid NOT NULL,
	"provider" text NOT NULL,
	"provider_user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"auth_provider_user_id" text NOT NULL,
	"email" text,
	"display_name" text,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "ask_families" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ask_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "ask_subject_photos" (
	"seq" bigserial NOT NULL,
	"ask_id" uuid NOT NULL,
	"photo_id" uuid NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "ask_subject_photos_ask_id_photo_id_pk" PRIMARY KEY("ask_id","photo_id")
);

CREATE TABLE "asks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"asker_person_id" uuid NOT NULL,
	"target_person_id" uuid NOT NULL,
	"question_text" text NOT NULL,
	"recording_media_id" uuid,
	"status" "ask_status" DEFAULT 'queued' NOT NULL,
	"story_id" uuid,
	"source_story_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"routed_at" timestamp with time zone,
	"answered_at" timestamp with time zone,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "consent_records" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"person_id" uuid NOT NULL,
	"story_id" uuid,
	"scope" text,
	"action" "consent_action" NOT NULL,
	"resulting_state" text NOT NULL,
	"approval_audio_media_id" uuid,
	"actor_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "erasure_audit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"item_type" text NOT NULL,
	"item_id" uuid NOT NULL,
	"owner_person_id" uuid NOT NULL,
	"actor_person_id" uuid NOT NULL,
	"reason" text NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "families" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"short_name" text,
	"description" text,
	"discoverable" boolean DEFAULT false NOT NULL,
	"creator_person_id" uuid NOT NULL,
	"steward_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "family_photo_families" (
	"photo_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"added_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "family_photo_families_photo_id_family_id_pk" PRIMARY KEY("photo_id","family_id")
);

CREATE TABLE "family_photos" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"contributor_person_id" uuid NOT NULL,
	"source" "photo_source" NOT NULL,
	"storage_key" text NOT NULL,
	"caption" text,
	"exif_captured_at" timestamp with time zone,
	"exif_gps" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "family_photos_storage_key_unique" UNIQUE("storage_key")
);

CREATE TABLE "follow_up_decisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"story_id" uuid NOT NULL,
	"thread_position" integer NOT NULL,
	"record_kind" "follow_up_record_kind" NOT NULL,
	"evaluator_model_id" text,
	"candidates" jsonb,
	"dispositions" jsonb,
	"selected_seed" text,
	"phrased_line" text,
	"policy" jsonb,
	"decision_id" uuid,
	"outcome" "follow_up_outcome",
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "google_photos_connections" (
	"person_id" uuid PRIMARY KEY NOT NULL,
	"encrypted_refresh_token" text NOT NULL,
	"google_account_email" text,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone
);

CREATE TABLE "intake_answers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"person_id" uuid NOT NULL,
	"question_key" text NOT NULL,
	"prompt_question" text NOT NULL,
	"origin" "intake_origin" NOT NULL,
	"media_id" uuid,
	"transcript" text,
	"text" text DEFAULT '' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "intake_revisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"intake_answer_id" uuid NOT NULL,
	"level" "prose_revision_level" NOT NULL,
	"text" text NOT NULL,
	"model_id" text,
	"prompt_text" text,
	"actor_person_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "invitations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"token_hash" text NOT NULL,
	"token_sealed" text,
	"family_id" uuid NOT NULL,
	"inviter_person_id" uuid NOT NULL,
	"invitee_person_id" uuid NOT NULL,
	"invitee_name" text,
	"invitee_email" text,
	"invitee_phone" text,
	"delivery_channels" text[],
	"delivered_at" timestamp with time zone,
	"delivery_error" text,
	"delivery_attempts" integer DEFAULT 0 NOT NULL,
	"relationship_label" text,
	"role" "membership_role" DEFAULT 'member' NOT NULL,
	"status" "invitation_status" DEFAULT 'pending' NOT NULL,
	"accepted_person_id" uuid,
	"expires_at" timestamp with time zone,
	"accepted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "join_requests" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"family_id" uuid NOT NULL,
	"requester_person_id" uuid NOT NULL,
	"message" text,
	"status" "join_request_status" DEFAULT 'pending' NOT NULL,
	"decided_by_person_id" uuid,
	"resulting_membership_id" uuid,
	"decided_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "kinship_assertions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"family_id" uuid NOT NULL,
	"edge_type" "kinship_edge_type" NOT NULL,
	"person_a_id" uuid NOT NULL,
	"person_b_id" uuid NOT NULL,
	"nature" "kinship_nature",
	"state" "kinship_state" DEFAULT 'asserted' NOT NULL,
	"actor_person_id" uuid NOT NULL,
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "kinship_assertions_no_self_ck" CHECK ("kinship_assertions"."person_a_id" <> "kinship_assertions"."person_b_id"),
	CONSTRAINT "kinship_assertions_nature_ck" CHECK (("kinship_assertions"."edge_type" = 'parent_of' AND "kinship_assertions"."nature" IS NOT NULL) OR ("kinship_assertions"."edge_type" = 'partnered_with' AND "kinship_assertions"."nature" IS NULL))
);

CREATE TABLE "kinship_subject_hides" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"family_id" uuid NOT NULL,
	"edge_type" "kinship_edge_type" NOT NULL,
	"person_a_id" uuid NOT NULL,
	"person_b_id" uuid NOT NULL,
	"subject_person_id" uuid NOT NULL,
	"hidden" boolean NOT NULL,
	"actor_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "link_sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"token_hash" text NOT NULL,
	"person_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"invited_by_person_id" uuid NOT NULL,
	"expires_at" timestamp with time zone,
	"revoked_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone
);

CREATE TABLE "media" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_person_id" uuid NOT NULL,
	"kind" "media_kind" NOT NULL,
	"storage_key" text NOT NULL,
	"content_type" text NOT NULL,
	"duration_seconds" integer,
	"checksum" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "memberships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"person_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"role" "membership_role" DEFAULT 'member' NOT NULL,
	"status" "membership_status" DEFAULT 'active' NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ended_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "mock_auth_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"auth_provider_user_id" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "persons" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"display_name" text,
	"spoken_name" text,
	"birth_year" integer,
	"birth_date" date,
	"death_year" integer,
	"death_date" date,
	"onboarded_at" timestamp with time zone,
	"biographical_anchors" jsonb DEFAULT '{}'::jsonb,
	"life_status" "life_status" DEFAULT 'living' NOT NULL,
	"sex" "person_sex" DEFAULT 'unknown',
	"origin" "person_origin" DEFAULT 'self' NOT NULL,
	"identified" boolean DEFAULT true NOT NULL,
	"account_id" uuid,
	"created_by_person_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "photo_people" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"photo_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"tagged_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "photo_places" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"photo_id" uuid NOT NULL,
	"place_id" uuid NOT NULL,
	"tagged_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "photo_subjects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"photo_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"tagged_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "places" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"family_id" uuid NOT NULL,
	"name" text NOT NULL,
	"exif_gps" jsonb,
	"created_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "prose_revisions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"seq" bigserial NOT NULL,
	"story_id" uuid NOT NULL,
	"level" "prose_revision_level" NOT NULL,
	"text" text NOT NULL,
	"model_id" text,
	"prompt_text" text,
	"actor_person_id" uuid,
	"story_recording_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "stories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"owner_person_id" uuid NOT NULL,
	"state" "story_state" DEFAULT 'draft' NOT NULL,
	"kind" "story_kind" DEFAULT 'voice' NOT NULL,
	"audience_tier" "audience_tier" DEFAULT 'private' NOT NULL,
	"recording_media_id" uuid,
	"transcript" text,
	"transcript_word_timings" jsonb,
	"prose" text,
	"title" text,
	"summary" text,
	"tags" jsonb DEFAULT '[]'::jsonb,
	"era_year" integer,
	"era_label" text,
	"prompt_question" text,
	"ask_id" uuid,
	"originating_family_id" uuid,
	"subject_photo_id" uuid,
	"processing_error" text,
	"processing_failed_at" timestamp with time zone,
	"processing_attempt" integer DEFAULT 0 NOT NULL,
	"approved_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_families" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"family_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_favorites" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"family_photo_id" uuid,
	"provenance" "story_image_provenance" DEFAULT 'family_photo' NOT NULL,
	"source_url" text,
	"license" text,
	"attribution" text,
	"thumbnail_url" text,
	"is_cover" boolean DEFAULT false NOT NULL,
	"position" integer NOT NULL,
	"attached_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_likes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_recordings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"position" integer NOT NULL,
	"media_id" uuid NOT NULL,
	"transcript" text,
	"transcript_word_timings" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_subjects" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"tagged_by_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "story_views" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"story_id" uuid NOT NULL,
	"person_id" uuid NOT NULL,
	"first_viewed_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "voice_captions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"photo_id" uuid NOT NULL,
	"media_id" uuid NOT NULL,
	"transcript" text,
	"owner_person_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "account_contacts" ADD CONSTRAINT "account_contacts_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "account_identities" ADD CONSTRAINT "account_identities_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ask_families" ADD CONSTRAINT "ask_families_ask_id_asks_id_fk" FOREIGN KEY ("ask_id") REFERENCES "public"."asks"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ask_families" ADD CONSTRAINT "ask_families_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "ask_subject_photos" ADD CONSTRAINT "ask_subject_photos_ask_id_asks_id_fk" FOREIGN KEY ("ask_id") REFERENCES "public"."asks"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "ask_subject_photos" ADD CONSTRAINT "ask_subject_photos_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "asks" ADD CONSTRAINT "asks_asker_person_id_persons_id_fk" FOREIGN KEY ("asker_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "asks" ADD CONSTRAINT "asks_target_person_id_persons_id_fk" FOREIGN KEY ("target_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "asks" ADD CONSTRAINT "asks_recording_media_id_media_id_fk" FOREIGN KEY ("recording_media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "asks" ADD CONSTRAINT "asks_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "asks" ADD CONSTRAINT "asks_source_story_id_stories_id_fk" FOREIGN KEY ("source_story_id") REFERENCES "public"."stories"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_approval_audio_media_id_media_id_fk" FOREIGN KEY ("approval_audio_media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "erasure_audit" ADD CONSTRAINT "erasure_audit_owner_person_id_persons_id_fk" FOREIGN KEY ("owner_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "erasure_audit" ADD CONSTRAINT "erasure_audit_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "families" ADD CONSTRAINT "families_creator_person_id_persons_id_fk" FOREIGN KEY ("creator_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "families" ADD CONSTRAINT "families_steward_person_id_persons_id_fk" FOREIGN KEY ("steward_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "family_photo_families" ADD CONSTRAINT "family_photo_families_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "family_photo_families" ADD CONSTRAINT "family_photo_families_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "family_photos" ADD CONSTRAINT "family_photos_contributor_person_id_persons_id_fk" FOREIGN KEY ("contributor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "follow_up_decisions" ADD CONSTRAINT "follow_up_decisions_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "follow_up_decisions" ADD CONSTRAINT "follow_up_decisions_decision_id_follow_up_decisions_id_fk" FOREIGN KEY ("decision_id") REFERENCES "public"."follow_up_decisions"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "google_photos_connections" ADD CONSTRAINT "google_photos_connections_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "intake_answers" ADD CONSTRAINT "intake_answers_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "intake_answers" ADD CONSTRAINT "intake_answers_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "intake_revisions" ADD CONSTRAINT "intake_revisions_intake_answer_id_intake_answers_id_fk" FOREIGN KEY ("intake_answer_id") REFERENCES "public"."intake_answers"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "intake_revisions" ADD CONSTRAINT "intake_revisions_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_inviter_person_id_persons_id_fk" FOREIGN KEY ("inviter_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_invitee_person_id_persons_id_fk" FOREIGN KEY ("invitee_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "invitations" ADD CONSTRAINT "invitations_accepted_person_id_persons_id_fk" FOREIGN KEY ("accepted_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "join_requests" ADD CONSTRAINT "join_requests_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "join_requests" ADD CONSTRAINT "join_requests_requester_person_id_persons_id_fk" FOREIGN KEY ("requester_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "join_requests" ADD CONSTRAINT "join_requests_decided_by_person_id_persons_id_fk" FOREIGN KEY ("decided_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "join_requests" ADD CONSTRAINT "join_requests_resulting_membership_id_memberships_id_fk" FOREIGN KEY ("resulting_membership_id") REFERENCES "public"."memberships"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_assertions" ADD CONSTRAINT "kinship_assertions_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_assertions" ADD CONSTRAINT "kinship_assertions_person_a_id_persons_id_fk" FOREIGN KEY ("person_a_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_assertions" ADD CONSTRAINT "kinship_assertions_person_b_id_persons_id_fk" FOREIGN KEY ("person_b_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_assertions" ADD CONSTRAINT "kinship_assertions_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_subject_hides" ADD CONSTRAINT "kinship_subject_hides_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_subject_hides" ADD CONSTRAINT "kinship_subject_hides_person_a_id_persons_id_fk" FOREIGN KEY ("person_a_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_subject_hides" ADD CONSTRAINT "kinship_subject_hides_person_b_id_persons_id_fk" FOREIGN KEY ("person_b_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_subject_hides" ADD CONSTRAINT "kinship_subject_hides_subject_person_id_persons_id_fk" FOREIGN KEY ("subject_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "kinship_subject_hides" ADD CONSTRAINT "kinship_subject_hides_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "link_sessions" ADD CONSTRAINT "link_sessions_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "link_sessions" ADD CONSTRAINT "link_sessions_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "link_sessions" ADD CONSTRAINT "link_sessions_invited_by_person_id_persons_id_fk" FOREIGN KEY ("invited_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "media" ADD CONSTRAINT "media_owner_person_id_persons_id_fk" FOREIGN KEY ("owner_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "persons" ADD CONSTRAINT "persons_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "persons" ADD CONSTRAINT "persons_created_by_person_id_persons_id_fk" FOREIGN KEY ("created_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_people" ADD CONSTRAINT "photo_people_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "photo_people" ADD CONSTRAINT "photo_people_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_people" ADD CONSTRAINT "photo_people_tagged_by_person_id_persons_id_fk" FOREIGN KEY ("tagged_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_places" ADD CONSTRAINT "photo_places_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "photo_places" ADD CONSTRAINT "photo_places_place_id_places_id_fk" FOREIGN KEY ("place_id") REFERENCES "public"."places"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_places" ADD CONSTRAINT "photo_places_tagged_by_person_id_persons_id_fk" FOREIGN KEY ("tagged_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_subjects" ADD CONSTRAINT "photo_subjects_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "photo_subjects" ADD CONSTRAINT "photo_subjects_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "photo_subjects" ADD CONSTRAINT "photo_subjects_tagged_by_person_id_persons_id_fk" FOREIGN KEY ("tagged_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "places" ADD CONSTRAINT "places_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "places" ADD CONSTRAINT "places_created_by_person_id_persons_id_fk" FOREIGN KEY ("created_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prose_revisions" ADD CONSTRAINT "prose_revisions_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prose_revisions" ADD CONSTRAINT "prose_revisions_actor_person_id_persons_id_fk" FOREIGN KEY ("actor_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "prose_revisions" ADD CONSTRAINT "prose_revisions_story_recording_id_story_recordings_id_fk" FOREIGN KEY ("story_recording_id") REFERENCES "public"."story_recordings"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stories" ADD CONSTRAINT "stories_owner_person_id_persons_id_fk" FOREIGN KEY ("owner_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stories" ADD CONSTRAINT "stories_recording_media_id_media_id_fk" FOREIGN KEY ("recording_media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stories" ADD CONSTRAINT "stories_originating_family_id_families_id_fk" FOREIGN KEY ("originating_family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "stories" ADD CONSTRAINT "stories_subject_photo_id_family_photos_id_fk" FOREIGN KEY ("subject_photo_id") REFERENCES "public"."family_photos"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_families" ADD CONSTRAINT "story_families_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_families" ADD CONSTRAINT "story_families_family_id_families_id_fk" FOREIGN KEY ("family_id") REFERENCES "public"."families"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_favorites" ADD CONSTRAINT "story_favorites_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_favorites" ADD CONSTRAINT "story_favorites_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_images" ADD CONSTRAINT "story_images_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_images" ADD CONSTRAINT "story_images_family_photo_id_family_photos_id_fk" FOREIGN KEY ("family_photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "story_images" ADD CONSTRAINT "story_images_attached_by_person_id_persons_id_fk" FOREIGN KEY ("attached_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_likes" ADD CONSTRAINT "story_likes_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_likes" ADD CONSTRAINT "story_likes_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_recordings" ADD CONSTRAINT "story_recordings_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_recordings" ADD CONSTRAINT "story_recordings_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_subjects" ADD CONSTRAINT "story_subjects_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_subjects" ADD CONSTRAINT "story_subjects_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_subjects" ADD CONSTRAINT "story_subjects_tagged_by_person_id_persons_id_fk" FOREIGN KEY ("tagged_by_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_views" ADD CONSTRAINT "story_views_story_id_stories_id_fk" FOREIGN KEY ("story_id") REFERENCES "public"."stories"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "story_views" ADD CONSTRAINT "story_views_person_id_persons_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "voice_captions" ADD CONSTRAINT "voice_captions_photo_id_family_photos_id_fk" FOREIGN KEY ("photo_id") REFERENCES "public"."family_photos"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "voice_captions" ADD CONSTRAINT "voice_captions_media_id_media_id_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE no action ON UPDATE no action;
ALTER TABLE "voice_captions" ADD CONSTRAINT "voice_captions_owner_person_id_persons_id_fk" FOREIGN KEY ("owner_person_id") REFERENCES "public"."persons"("id") ON DELETE no action ON UPDATE no action;
CREATE UNIQUE INDEX "account_contacts_kind_value_uq" ON "account_contacts" USING btree ("kind","value");
CREATE INDEX "account_contacts_account_id_idx" ON "account_contacts" USING btree ("account_id");
CREATE UNIQUE INDEX "account_identities_provider_user_uq" ON "account_identities" USING btree ("provider","provider_user_id");
CREATE INDEX "account_identities_account_id_idx" ON "account_identities" USING btree ("account_id");
CREATE UNIQUE INDEX "accounts_auth_provider_user_id_uq" ON "accounts" USING btree ("auth_provider_user_id");
CREATE UNIQUE INDEX "ask_families_ask_family_uq" ON "ask_families" USING btree ("ask_id","family_id");
CREATE INDEX "ask_families_ask_idx" ON "ask_families" USING btree ("ask_id");
CREATE INDEX "ask_families_family_idx" ON "ask_families" USING btree ("family_id");
CREATE INDEX "ask_subject_photos_photo_idx" ON "ask_subject_photos" USING btree ("photo_id");
CREATE INDEX "asks_target_idx" ON "asks" USING btree ("target_person_id");
CREATE INDEX "asks_status_idx" ON "asks" USING btree ("status");
CREATE INDEX "asks_source_story_idx" ON "asks" USING btree ("source_story_id");
CREATE INDEX "consent_person_idx" ON "consent_records" USING btree ("person_id");
CREATE INDEX "consent_story_idx" ON "consent_records" USING btree ("story_id");
CREATE INDEX "family_photo_families_family_idx" ON "family_photo_families" USING btree ("family_id");
CREATE INDEX "family_photos_contributor_idx" ON "family_photos" USING btree ("contributor_person_id");
CREATE INDEX "follow_up_decisions_story_idx" ON "follow_up_decisions" USING btree ("story_id");
CREATE INDEX "intake_answers_person_idx" ON "intake_answers" USING btree ("person_id");
CREATE UNIQUE INDEX "intake_answers_person_question_uq" ON "intake_answers" USING btree ("person_id","question_key");
CREATE INDEX "intake_revisions_answer_idx" ON "intake_revisions" USING btree ("intake_answer_id");
CREATE UNIQUE INDEX "invitations_token_hash_uq" ON "invitations" USING btree ("token_hash");
CREATE INDEX "invitations_family_idx" ON "invitations" USING btree ("family_id");
CREATE INDEX "join_requests_family_idx" ON "join_requests" USING btree ("family_id");
CREATE INDEX "join_requests_requester_idx" ON "join_requests" USING btree ("requester_person_id");
CREATE INDEX "join_requests_status_idx" ON "join_requests" USING btree ("status");
CREATE INDEX "kinship_assertions_edge_idx" ON "kinship_assertions" USING btree ("family_id","edge_type","person_a_id","person_b_id");
CREATE INDEX "kinship_assertions_person_a_idx" ON "kinship_assertions" USING btree ("person_a_id");
CREATE INDEX "kinship_assertions_person_b_idx" ON "kinship_assertions" USING btree ("person_b_id");
CREATE INDEX "kinship_subject_hides_edge_subject_idx" ON "kinship_subject_hides" USING btree ("family_id","edge_type","person_a_id","person_b_id","subject_person_id");
CREATE UNIQUE INDEX "link_sessions_token_hash_uq" ON "link_sessions" USING btree ("token_hash");
CREATE INDEX "link_sessions_person_idx" ON "link_sessions" USING btree ("person_id");
CREATE INDEX "media_owner_idx" ON "media" USING btree ("owner_person_id");
CREATE INDEX "memberships_person_idx" ON "memberships" USING btree ("person_id");
CREATE INDEX "memberships_family_idx" ON "memberships" USING btree ("family_id");
CREATE UNIQUE INDEX "mock_auth_users_email_uq" ON "mock_auth_users" USING btree ("email");
CREATE UNIQUE INDEX "mock_auth_users_provider_id_uq" ON "mock_auth_users" USING btree ("auth_provider_user_id");
CREATE UNIQUE INDEX "persons_account_id_uq" ON "persons" USING btree ("account_id");
CREATE UNIQUE INDEX "photo_people_photo_person_uq" ON "photo_people" USING btree ("photo_id","person_id");
CREATE INDEX "photo_people_photo_idx" ON "photo_people" USING btree ("photo_id");
CREATE INDEX "photo_people_person_idx" ON "photo_people" USING btree ("person_id");
CREATE UNIQUE INDEX "photo_places_photo_place_uq" ON "photo_places" USING btree ("photo_id","place_id");
CREATE INDEX "photo_places_photo_idx" ON "photo_places" USING btree ("photo_id");
CREATE INDEX "photo_places_place_idx" ON "photo_places" USING btree ("place_id");
CREATE UNIQUE INDEX "photo_subjects_photo_person_uq" ON "photo_subjects" USING btree ("photo_id","person_id");
CREATE INDEX "photo_subjects_photo_idx" ON "photo_subjects" USING btree ("photo_id");
CREATE INDEX "photo_subjects_person_idx" ON "photo_subjects" USING btree ("person_id");
CREATE UNIQUE INDEX "places_family_name_uq" ON "places" USING btree ("family_id","name");
CREATE INDEX "places_family_idx" ON "places" USING btree ("family_id");
CREATE INDEX "prose_revisions_story_idx" ON "prose_revisions" USING btree ("story_id");
CREATE INDEX "stories_owner_idx" ON "stories" USING btree ("owner_person_id");
CREATE INDEX "stories_state_idx" ON "stories" USING btree ("state");
CREATE UNIQUE INDEX "story_families_story_family_uq" ON "story_families" USING btree ("story_id","family_id");
CREATE INDEX "story_families_story_idx" ON "story_families" USING btree ("story_id");
CREATE INDEX "story_families_family_idx" ON "story_families" USING btree ("family_id");
CREATE UNIQUE INDEX "story_favorites_story_person_uq" ON "story_favorites" USING btree ("story_id","person_id");
CREATE INDEX "story_favorites_person_idx" ON "story_favorites" USING btree ("person_id");
CREATE INDEX "story_images_story_idx" ON "story_images" USING btree ("story_id");
CREATE UNIQUE INDEX "story_images_story_position_uq" ON "story_images" USING btree ("story_id","position");
CREATE UNIQUE INDEX "story_images_story_photo_uq" ON "story_images" USING btree ("story_id","family_photo_id");
CREATE UNIQUE INDEX "story_likes_story_person_uq" ON "story_likes" USING btree ("story_id","person_id");
CREATE INDEX "story_likes_person_idx" ON "story_likes" USING btree ("person_id");
CREATE INDEX "story_recordings_story_idx" ON "story_recordings" USING btree ("story_id");
CREATE UNIQUE INDEX "story_recordings_story_position_uq" ON "story_recordings" USING btree ("story_id","position");
CREATE UNIQUE INDEX "story_subjects_story_person_uq" ON "story_subjects" USING btree ("story_id","person_id");
CREATE INDEX "story_subjects_story_idx" ON "story_subjects" USING btree ("story_id");
CREATE INDEX "story_subjects_person_idx" ON "story_subjects" USING btree ("person_id");
CREATE UNIQUE INDEX "story_views_story_person_uq" ON "story_views" USING btree ("story_id","person_id");
CREATE INDEX "story_views_person_idx" ON "story_views" USING btree ("person_id");
CREATE INDEX "voice_captions_photo_idx" ON "voice_captions" USING btree ("photo_id");
