/**
 * Regenerate drizzle/schema.sql — the single full-schema DDL — from src/schema.ts.
 *
 * Single-schema dev model: there is NO incremental migration chain. Edit src/schema.ts, run
 * `pnpm --filter @chronicle/db db:generate`, then reseed (which blows the dev DB away and applies
 * this file + invariants.sql). See src/migrate.ts.
 */
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const PKG_DIR = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(PKG_DIR, "drizzle/schema.sql");

const HEADER = [
  "-- GENERATED by `pnpm --filter @chronicle/db db:generate` (drizzle-kit export from src/schema.ts).",
  "-- The single full-schema DDL. Do NOT hand-edit — edit src/schema.ts and regenerate.",
  "-- Structural invariants drizzle can't model (triggers, partial unique indexes) live in",
  "-- invariants.sql and are applied right after this file. See src/migrate.ts.",
  "",
  "",
].join("\n");

// Shell invocation so Windows resolves the `drizzle-kit` shim (.cmd) from node_modules/.bin, which
// the npm-script PATH puts in scope. `drizzle-kit export` prints the full DDL to stdout.
const ddl = execSync("drizzle-kit export --config drizzle.config.ts", {
  cwd: PKG_DIR,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "inherit"],
});

writeFileSync(OUT, HEADER + ddl);
console.log(`wrote ${OUT} (${ddl.split("\n").length} lines of DDL)`);

// Also emit an incremental migration for the drizzle-modeled diff. drizzle-kit generate diffs
// schema.ts against meta/*_snapshot.json and writes a new NNNN_*.sql only when something changed
// (it prints "No schema changes" and writes nothing otherwise). Invariant changes are NOT captured
// here — hand-carry them into the emitted migration (see docs/DECISIONS.md § Migrations).
execSync("drizzle-kit generate", {
  cwd: PKG_DIR,
  encoding: "utf8",
  stdio: ["ignore", "inherit", "inherit"],
});
console.log("db:generate done — if a new migration was written, hand-carry any invariant changes into it.");
